-- DISPLAY DATA FROM TABLES

-- DISPLAY DATA FROM VIEWS

-- [1] HOW MANY CUSTOMERS DOES THE BANK HAVE?

-- [2.A] WHAT IS THE DISTRIBUTION OF CUSTOMERS ACROSS EACH STATE?
-- [2.B] WHAT IS THE DISTRIBUTION OF CUSTOMERS ACROSS EACH CITY?

-- [3] HOW MANY SUPPORT QUERIES HAVE BEEN RAISED?
    
-- [4] HOW MANY SUPPORT REPRESENTATIVES DOES THE BANK CURRENTLY HAVE? 
    
-- [5] HOW MANY SUPPORT QUERIES ARE HANDLED BY EACH SUPPORT REPRESENTATIVE? 
-- WHO ARE THE EMPLOYEES THAT HAVE HANDLED MORE THE 250 QUERIES?

-- [6] WHAT ARE THE DIFFERENT SUPPORT QUERY CATEGORIES AND HOW IS THEIR QUANTITY DISTRIBUTED?

-- [7] WHICH REGION (STATE AND CITY) HAS REPORTED THE MOST SUPPORT QUERIES?

-- [8] WHAT IS THE DISTRIBUTION OF SUPPORT QUERY TYPES ACROSS EACH CITY AND STATE?

-- [9] ARE THERE ANY CUSTOMER(s) WHO HAVE RAISED 3 OR MORE SUPPORT QUERIES?

-- [10] CALCULATE THE CALL DURATION FOR EACH SUPPORT REPRESENTATIVE PER WEEK AND PER DAY IN HOURS
-- ASSUME THE SUPPORT REPRESENTATIVES WORK 5 DAYS IN A WEEK

-- [11] CATEGORIZE THE WORK HOURS INTO 
   -- 1. OVER TIME : IF THE WORK HOURS PER DAY IS MORE THAN 8 HOURS PER DAY 
   -- 2. FIXED TIME : IF THE WORK HOURS IS EXACTLY 8 HOURS PER DAY
   -- 3. LESS THAN SHIFT HOURS : IF THE WORK HOURS IS LESS THAN 8 HOURS PER DAY
-- WRITE A FUNCTION TO DO THIS

-- [12] FIND HOW MANY HOME LOAN QUERIES HAVE BEEN RAISED IN EACH BRANCH 
-- WHICH BRANCH HAS REPORTED THE MOST HOME LOAN QUERIES? 

-- [13] FIND THE CUSTOMER and BRANCH DETAILS ABOUT SUPPORT QUERIES WHOSE CALL DURATION IS MORE THAN 8 MINUTES
