-- DISPLAY DATA FROM TABLES
SELECT * FROM BANK_T LIMIT 10;
SELECT * FROM BANK_BRANCH_T LIMIT 10;
SELECT * FROM BANK_CUSTOMER_T LIMIT 10;
SELECT * FROM BANK_EMPLOYEES_T LIMIT 10;
SELECT * FROM BANK_SUPPORT_QUERY_T LIMIT 10;

-- DISPLAY DATA FROM VIEWS
SELECT * FROM BANKING_SUPPORT_QUERY_BRANCH_V LIMIT 10;
SELECT * FROM BANKING_SUPPORT_QUERY_CUSTOMER_V LIMIT 10;
SELECT * FROM BANKING_SUPPORT_QUERY_BRANCH_V LIMIT 10;

-- [1] HOW MANY CUSTOMERS DOES THE BANK HAVE?
SELECT 
	COUNT(DISTINCT CUSTOMER_ID) AS NUMBER_OF_CUSTOMERS
FROM
	BANK_CUSTOMER_T;

-- [2.A] WHAT IS THE DISTRIBUTION OF CUSTOMERS ACROSS EACH STATE?
-- [2.B] WHAT IS THE DISTRIBUTION OF CUSTOMERS ACROSS EACH CITY?
SELECT 
	BRANCH_STATE,
    COUNT(CUSTOMER_ID) AS NUMBER_OF_CUSTOMERS
FROM
	BANK_BRANCH_T
JOIN
	BANK_CUSTOMER_T
USING(BRANCH_ID)
GROUP BY 1
ORDER BY 2 DESC;

SELECT 
	BRANCH_CITY,
    COUNT(CUSTOMER_ID) AS NUMBER_OF_CUSTOMERS
FROM
	BANK_BRANCH_T
JOIN
	BANK_CUSTOMER_T
USING(BRANCH_ID)
GROUP BY 1
ORDER BY 2 DESC;

-- [3] HOW MANY SUPPORT QUERIES HAVE BEEN RAISED?
SELECT 
	COUNT(SUPPORT_QUERY_ID) TOTAL_QUERIES
FROM 
	BANK_SUPPORT_QUERY_T;
    
-- [4] HOW MANY SUPPORT REPRESENTATIVES DOES THE BANK CURRENTLY HAVE? 
SELECT
	COUNT(DISTINCT SUPPORT_REPRESENTATIVE_ID) AS NUMBER_OF_SUPPORT_REPRESENTATIVES
FROM
	BANK_SUPPORT_QUERY_T;
    
-- [5] HOW MANY SUPPORT QUERIES ARE HANDLED BY EACH SUPPORT REPRESNTATIVE? 
-- WHO ARE THE EMPLOYEES THAT HAVE HANDLED MORE THE 250 QUERIES?
SELECT 
	SUPPORT_REPRESENTATIVE_ID,
    EMPLOYEE_NAME,
    COUNT(SUPPORT_REPRESENTATIVE_ID) AS NUMBER_OF_SUPPORT_QUERIES
FROM
	BANKING_SUPPORT_QUERY_EMPLOYEE_V
GROUP BY 1
HAVING NUMBER_OF_SUPPORT_QUERIES > 250;

-- [6] WHAT ARE THE DIFFERENT SUPPORT QUERY CATEGORIES AND HOW IS THEIR QUANTITY DISTRIBUTED?
SELECT
	SUPPORT_QUERY_TYPE,
    COUNT(SUPPORT_QUERY_TYPE) AS NUMBER_OF_QUERIES
FROM
	BANK_SUPPORT_QUERY_T
GROUP BY 1
ORDER BY 2 DESC;

-- [7] WHICH REGION (STATE AND CITY) HAS REPORTED THE MOST SUPPORT QUERIES?
SELECT 
    BRANCH_CITY,
    COUNT(SUPPORT_QUERY_ID) AS TOTAL_SUPPORT_QUERIES
FROM 
	BANKING_SUPPORT_QUERY_BRANCH_V
GROUP BY 1
ORDER BY 2 DESC;

SELECT 
    BRANCH_STATE,
    COUNT(SUPPORT_QUERY_ID) AS TOTAL_SUPPORT_QUERIES
FROM 
	BANKING_SUPPORT_QUERY_BRANCH_V
GROUP BY 1
ORDER BY 2 DESC;

-- [8] WHAT IS THE DISTRIBUTION OF SUPPORT QUERY TYPES ACROSS EACH CITY AND STATE?
SELECT 
    BRANCH_CITY,
    BRANCH_STATE,
    SUPPORT_QUERY_TYPE,
    COUNT(*) AS TOTAL_SUPPORT_QUERIES
FROM 
	BANKING_SUPPORT_QUERY_BRANCH_V
GROUP BY 1,2,3
ORDER BY 4 DESC;

-- [9] ARE THERE ANY CUSTOMER(s) WHO HAVE RAISED 3 OR MORE SUPPORT QUERIES?
SELECT 
	CUSTOMER_ID,
    COUNT(SUPPORT_QUERY_ID) AS TOTAL_NUMBER_OF_QUERIES
FROM
	BANKING_SUPPORT_QUERY_CUSTOMER_V
GROUP BY 1
HAVING TOTAL_NUMBER_OF_QUERIES >= 3
ORDER BY 2 DESC;

-- [10] CALCULATE THE CALL DURATION FOR EACH SUPPORT REPRESENTATIVE PER WEEK AND PER DAY IN HOURS
-- ASSUME THE SUPPORT REPRESENTATIVES WORK 5 DAYS IN A WEEK
SELECT
	SUPPORT_REPRESENTATIVE_ID,
    SUM(CALL_DURATION)/60 AS TOTAL_CALL_DURATION_PER_WEEK,
    SUM(CALL_DURATION)/60/5 TOTAL_CALL_DURATION_PER_DAY
FROM
	BANK_SUPPORT_QUERY_T
GROUP BY 1;

-- [11] CATEGORIZE THE WORK HOURS INTO 
   -- 1. OVER TIME : IF THE WORK HOURS PER DAY IS MORE THAN 8 HOURS PER DAY 
   -- 2. FIXED TIME : IF THE WORK HOURS IS EXACTLY 8 HOURS PER DAY
   -- 3. LESS THAN SHIFT HOURS : IF THE WORK HOURS IS LESS THAN 8 HOURS PER DAY
-- WRITE A FUNCTION TO DO THIS
SELECT
	SUPPORT_REPRESENTATIVE_ID,
	WORK_HOURS_F(SUM(CALL_DURATION)/60/5) AS WORK_HOURS
FROM
	BANK_SUPPORT_QUERY_T
GROUP BY 1;

-- [12] FIND HOW MANY HOME LOAN QUERIES HAVE BEEN RAISED IN EACH BRANCH 
-- WHICH BRANCH HAS REPORTED THE MOST HOME LOAN QUERIES? 
SELECT 
	BRANCH_ID,
    BRANCH_STATE,
    BRANCH_CITY,
    COUNT(*) AS NUMBER_OF_HOME_LOAN_QUERIES
FROM 
	banking_support_query_branch_v
WHERE
	SUPPORT_QUERY_TYPE = 'HOME LOAN'
GROUP BY 1,2,3
ORDER BY 4 DESC;

-- [13] FIND THE CUSTOMER and BRANCH DETAILS ABOUT SUPPORT QUERIES WHOSE CALL DURATION IS MORE THAN 8 MINUTES
SELECT 
	SQC.CUSTOMER_ID, 
    SQB.BRANCH_ID,
    SQB.BRANCH_STATE,
    SQB.BRANCH_CITY,
    SQC.SUPPORT_QUERY_ID, 
    SQC.SUPPORT_QUERY_TYPE,
    SQC.SUPPORT_REPRESENTATIVE_ID,
    SQC.CALL_DURATION
FROM banking_support_query_customer_v SQC
JOIN banking_support_query_branch_v SQB
USING(SUPPORT_QUERY_ID)
WHERE SQC.CALL_DURATION >= 8; 
