CREATE TABLE gl_eats_ord_t (
	ORDER_ID INTEGER,
	DELIVERY_EMP_ID INTEGER,
	CUSTOMER_ID INTEGER,
	RESTAURANT_ID INTEGER,
	ORDER_COST INTEGER,
	ORDER_ITEMS INTEGER,
	DISCOUNT INTEGER,
	WEEK_NUMBER INTEGER,
	PRIMARY KEY (ORDER_ID)
);

-- DROP TABLE gl_eats_ord_t;