CREATE TABLE gl_eats_del_t (	
	DELIVERY_ID INTEGER,
	DELIVERY_EMP_ID INTEGER,
	ORDER_ID INTEGER,
	DELIVERY_STATUS VARCHAR(10),
	RESTAURANT_ID INTEGER,
	STAR_RATING INTEGER,
	WEEK_NUMBER INTEGER,
	PRIMARY KEY (DELIVERY_ID)
);

-- DROP TABLE gl_eats_del_t;
