CREATE TABLE gl_eats_rest_t (
	RESTAURANT_ID INTEGER,
	RESTAURANT_NAME VARCHAR(60),
	CITY_NAME VARCHAR(60),
        COUNTRY_CD VARCHAR(60),
	ADDRESS VARCHAR(100),
	LOCALITY VARCHAR(100),
	LATITUDE DECIMAL(14,8),
	LONGITUDE DECIMAL(14,8),
	CUISINES VARCHAR(100),
	RESTAURANT_RATING DECIMAL(2,1),
	PRIMARY KEY (RESTAURANT_ID)
);

-- DROP TABLE gl_eats_rest_t;
