CREATE TABLE gl_eats_cust_t (
	CUSTOMER_ID INTEGER,
	CUSTOMER_NAME VARCHAR(20),
	EMAIL_ADDRESS VARCHAR(50),
	COUNTRY_CD VARCHAR(15),
	PRIMARY KEY (CUSTOMER_ID)
);

-- DROP TABLE gl_eats_cust_t;