-- Normalizing the data, Customer Information

CREATE TABLE customer_t (
	CUSTOMER_ID VARCHAR(25),
    CUSTOMER_NAME VARCHAR(25),
    GENDER VARCHAR(15),
    JOB_TITLE VARCHAR(50),
    PHONE_NUMBER VARCHAR(20),
    EMAIL_ADDRESS VARCHAR(50),
    CITY VARCHAR(25),
    COUNTRY VARCHAR(40),
    STATE VARCHAR(40),
    CUSTOMER_ADDRESS VARCHAR(50),
    POSTAL_CODE INTEGER,
	CREDIT_CARD_TYPE VARCHAR(40),
    CREDIT_CARD_NUMBER BIGINT,
    PRIMARY KEY (CUSTOMER_ID)
);