-- Normalizing the data, Order Information

CREATE TABLE order_t (
    ORDER_ID VARCHAR(25),
	CUSTOMER_ID VARCHAR(25),
    SHIPPER_ID INTEGER,
    PRODUCT_ID INTEGER,
    QUANTITY INTEGER,
    VEHICLE_PRICE DECIMAL(14 , 2 ),
    ORDER_DATE DATE,
    SHIP_DATE DATE,
    DISCOUNT DECIMAL(4 , 2 ),
    SHIP_MODE VARCHAR(25),
    SHIPPING VARCHAR(30),
    CUSTOMER_FEEDBACK VARCHAR(20),
    QUARTER_NUMBER INTEGER,
    PRIMARY KEY (ORDER_ID)
);