DELIMITER $$ 
CREATE PROCEDURE gl_eats_p()
BEGIN
	INSERT INTO gl_eats.gl_eats_t (
		WEEK_NUMBER,
		CUSTOMER_ID,
		CUSTOMER_NAME,
		COUNTRY_CD,
		EMAIL_ADDRESS,
		ORDER_ID,
		ORDER_COST,
		ORDER_ITEMS,
		DISCOUNT,
		DELIVERY_EMP_ID,
		DELIVERY_ID,
		STAR_RATING,
		DELIVERY_STATUS,
		RESTAURANT_ID,
		RESTAURANT_NAME,
		CITY_NAME,
		ADDRESS,
		LOCALITY,
		LONGITUDE,
		LATITUDE,
		CUISINES,
		RESTAURANT_RATING
	) SELECT * FROM gl_eats.temp_t;
END;

-- CALL gl_eats_p();
