DELIMITER $$
CREATE PROCEDURE gl_eats_cust_p()
BEGIN
	INSERT INTO gl_eats_cust_t (
        CUSTOMER_ID, 
        CUSTOMER_NAME, 
        EMAIL_ADDRESS, 
        COUNTRY_CD
    )
    SELECT DISTINCT 
	CUSTOMER_ID, 
        CUSTOMER_NAME, 
        EMAIL_ADDRESS, 
        COUNTRY_CD 
	FROM gl_eats_t WHERE CUSTOMER_ID NOT IN (SELECT DISTINCT CUSTOMER_ID FROM gl_eats_cust_t);
END;
